### ISSUE TITLE
Unable to edit or delete module if you use a bad repo path

### ISSUE THREAD

**Issue by skunklabz** [cyclops-ui/cyclops#336] opened 2024-06-16 02:03 UTC
**Describe the bug**
Unable to view the details of a module that was created using a bad repo path. You are just given a "Page not found :/" error and no option to edit or delete the module. 

**To Reproduce**
1. Go to 'http://localhost:3000/modules'
2. Click on 'Add module'
3. Under the "Module template" section type in a bad repo URL and/or path
4. Give the module a name and click Save.
5. In the Deploy Modules page click the Details button of the bad module
![image](https://github.com/cyclops-ui/cyclops/assets/13306474/81c4b709-0c0c-4b69-bde7-6ee1d2b8b688)

**Expected behavior**
I'm expecting to be able to view the details of all modules, regardless of whether or not they have a bad repo URL, or path. Instead I'm given a simple 'Page not found :/' and no option to do anything else. 

**Screenshots**
![image](https://github.com/cyclops-ui/cyclops/assets/13306474/dc5264cc-54b6-417b-a57a-67b7c0b62130)

**Desktop (please complete the following information):**
 - OS: macOS (latest)
 - Browser Chrome 
 - Version latest

**Comment by petar-cvit** [comment] 2024-07-23 12:19
@skunklabz sorry for the delayed response. We have revamped the flow and removed the details button, and now the whole module card is clickable and will show you the module details page.

However, if you create a module with a bad repo URL, if you click directly on it, it will still take you to the page not found. We should disable the link if its a valid address. [Here](https://github.com/cyclops-ui/cyclops/blob/b7ea3fdd1e9a604602950bedac8ba17c2cc72d86/cyclops-ui/src/components/pages/Modules/Modules.tsx#L155) is the code for the link rendering that needs fixing. The issue is not as severe is as it was, but we should still fix it.

**Comment by s-vamshi** [comment] 2024-07-26 15:42
hi @petar-cvit i would love to work on this issue, can you please assign this to me?

**Comment by petar-cvit** [comment] 2024-07-26 15:44
Hey @s-vamshi, sure

**Comment by s-vamshi** [comment] 2024-07-27 07:00
@petar-cvit here are the things i have noticed,
1. will adding a new template reference, when we give a bad url or path it is showing an alert, so now we can't create module with bad url of module template.
![image](https://github.com/user-attachments/assets/e987c3af-6c58-41b4-bae0-f0f3ecffa0d4)
3. when we create a new module, we will be displayed with a module card which shows repo, path links and version.
- now when i click on path it eats the current page and redirects to the github page
- this github page shows 404 page as shown below
![image](https://github.com/user-attachments/assets/f97e5b98-7dea-4b9a-a559-9c182e783b91)
- when we create a template without version and use it for a module then it shows card with path url which gives the below error.
![image](https://github.com/user-attachments/assets/6758abc0-a94d-4244-920a-c45959aeaa00)

- can you please clarify if I need to remove the version(version+resolvedVersion) from the url which makes it valid or disable the path link(in this case i think we should check beforehand where url is valid or not using this api _/templates/store/_  ig

**Comment by petar-cvit** [comment] 2024-07-27 09:31
Hey @s-vamshi
- I agree it would be better if it opened a new window instead of opening in the same
- And yeah, this seems like a bug. Currently, the `getTemplateVersion` function is used to calculate the version for the link. Unfortunatly, that function is used to format the version you see in the card so it doesn't work as a link.
  - Could you fix it by adding the `templateResolvedVersion` in the link? If it is not provided, you can use the `version`, and if not, you can fall back to "main"

**Comment by s-vamshi** [comment] 2024-07-27 10:21
hi @petar-cvit , 
as i see resolvedVersion is generated from the back end and even if we use it in the link it is going to break and same goes with the version ig. any thoughts on this?

**Comment by petar-cvit** [comment] 2024-07-27 10:25
So if the repo is valid and you have a resolvedVersion the link as follows should work:
```
<repo>/tree/<resolvedVersion>/path
```
You can check if the link is valid if it starts with `https://github.com`. If it doesn't, you can skip generating the link

**Closed** 2024-07-27 12:45 UTC
Labels: bug, good first issue, UI
